config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :activities
  end
  resources :project_states
  resources :activities
  resources :batch_activities

  resources :employees do
    resources :timesheets do
      collection do
        post :start
      end
    end
    resources :activities
  end

  resources :people do
    resources :activities
  end
end

app/controllers/batch_activities_controller.rb
class BatchActivitiesController < ApplicationController
  def new
    # Allow callers specifying defaults
    @date = params[:date] || Date.today

    # TODO: only employees currently working for tenant
    people = current_tenant.company.employees

    @activities = people.map{|person|
      person.activities.build(:project => person.latest_project)
    }
  end

  def create
    date = Date.parse(params[:batch_activities][:date])
    @activites = params[:activities].collect{|activity_params|
      Activity.create(activity_params.merge(:date => date))
    }

    redirect_to activities_path(:by_date => date.to_s(:db))
  end
end

app/views/batch_activities/_form.html.haml
= simple_form_for :batch_activities, :url => batch_activities_path do |f|
  = f.input :date, :as => :date_field, :label => t('attributes.date'), :input_html => {:value => @date}

  %table.table.table-striped.collection
    %thead
      %th= t_attr :person, Activity
      %th= t_attr :project, Activity
      %th{:style => 'width: 5em'}= t_attr :duration, Activity
      %th= t_attr :remarks, Activity

    %tbody
    - for activity in @activities
      %tr
        = fields_for 'activities[]', activity do |a|
          %td
            = link_to activity.person, activity.person
            = a.hidden_field :person_id
          %td= a.select :project_id, Project.all.map{|project| [project.to_s, project.id]}, {:prompt => t_select_prompt(Project)}
          %td= a.text_field :duration
          %td= a.text_field :remarks

  = f.button :submit

app/views/batch_activities/new.html.haml
= boot_page_title

= render 'form'