config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :activities
  end
  resources :project_states
  resources :activities
  resources :batch_activities

  resources :employees do
    resources :timesheets do
      collection do
        post :start
      end
    end
    resources :activities
  end

  resources :people do
    resources :activities
  end
end

app/models/bookyt_projects/person.rb
module BookytProjects
  module Person
    extend ActiveSupport::Concern

    included do
      has_many :activities, :foreign_key => :person_id, :dependent => :destroy
      has_many :work_days, :foreign_key => :person_id, :dependent => :destroy
    end

    def latest_project
      activities.order(:date).last.try(:project)
    end

    def uses_timetracker?
      work_days.present?
    end
  end
end

app/views/people/_show_activities.html.haml
- @activities = resource.activities.where(:date => current_month_period(:by_period)).by_project_id(params[:by_project_id])
- if @activities.empty?
  = boot_no_entry_alert
  .activities.collection

- else
  = render 'activities/list', :collection => @activities unless @activities.empty?

.form-actions
  = icon_link_to :new, new_person_activity_path(resource)

= render 'activities/sidebar'

app/views/people/_show_timesheet.html.haml
- if @employee.work_days.empty?
  = boot_no_entry_alert

  = simple_form_for :timesheet, :url => start_employee_timesheets_url(@employee) do |f|
    = f.input :duration_from, :as => :date_field
    .form-actions
      = f.button :submit

- else
  - WorkDay.create_or_update_upto(@employee, Date.today.end_of_month)
  .row-fluid
    .span12
      = render 'timesheets/show', :work_days => @employee.work_days.where(:date => current_month_period(:by_period))

= render 'activities/sidebar'