config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :activities
  end
  resources :project_states
  resources :activities
  resources :batch_activities

  resources :employees do
    resources :timesheets do
      collection do
        post :start
      end
    end
    resources :activities
  end

  resources :people do
    resources :activities
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :client, :class_name => 'Person'
  belongs_to :project_state
  has_many :activities
  
  def to_s
    name
  end
end

app/controllers/projects_controller.rb
class ProjectsController < AuthorizedController
end

app/views/projects/_form.html.haml
= simple_form_for @project do |f|
  .row-fluid
    .span6
      = f.input :name, :input_html => {'data-autofocus' => 'true'}
      = f.input :duration_from, :as => :date_field
      = f.association :client, :as => :combobox
    .span6
      = f.association :project_state
      = f.input :duration_to, :as => :date_field
  .row-fluid
    .span12
      = f.input :remarks, :input_html => {:rows => 5}

  = f.button :submit

app/views/projects/_list.html.haml
%table.table.table-striped.activities.collection
  %thead
    %tr
      %th= t_attr :name
      %th= t_attr :client
      %th= t_attr :duration
      %th.action-links

  %tbody
    =render collection

app/views/projects/_project.html.haml
%tr
  %td= link_to project.name, project, {'data-href-container' => 'tr'}
  %td= project.client
  %td= [project.duration_from, project.duration_to].compact.join(' - ')
  %td.action-links
    = list_link_for(:edit, project)
    = list_link_for(:delete, project)

app/views/projects/_show.html.haml
.tabbable
  %ul.nav.nav-tabs
    %li.active= link_to 'Details', '#tab-details', {:data => {:toggle => 'tab'}}
    %li= link_to t_title(:list, Activity), '#tab-activities', {:data => {:toggle => 'tab'}}

.tab-content
  #tab-details.tab-pane.active
    = render "form"
  #tab-activities.tab-pane
    = render 'show_activities'

app/views/projects/_show_activities.html.haml
- @activities = resource.activities.where(:date => current_month_period(:by_period))
- if @activities.empty?
  = boot_no_entry_alert
  .activities.collection

- else
  = render 'activities/list', :collection => @activities unless @activities.empty?

.form-actions
  = icon_link_to :new, new_project_activity_path(resource)