config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :activities
  end
  resources :project_states
  resources :activities
  resources :batch_activities

  resources :employees do
    resources :timesheets do
      collection do
        post :start
      end
    end
    resources :activities
  end

  resources :people do
    resources :activities
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  def index
    @employee = Employee.find(params[:employee_id])
    WorkDay.create_or_update_upto(@employee, Date.today.end_of_month)
    range = Date.today.beginning_of_month..Date.today.end_of_month
    @work_days = @employee.work_days.where(:date => range)
  end

  def start
    @employee = Employee.find(params[:employee_id])
    @employee.work_days.create(:date => params[:timesheet][:duration_from])

    redirect_to @employee
  end
end

app/helpers/timesheet_helper.rb
module TimesheetHelper
  # Calculate classes for WorkDay rows
  #
  # We add a 0.5h margin when determine over/undertime.
  # Days in the future get the 'future' class.
  def work_day_classes(day)
    # No classes for days in the future
    return 'future' if day.date > Date.today

    classes = []

    # TODO: make a setting
    # +/- 0.5h is good
    margin = 0.5

    if day.overtime > margin
      classes << 'overtime'
    elsif day.overtime < -margin
      classes << 'undertime'
    elsif day.hours_due == 0.0
      classes << 'free'
    else
      classes << 'due_hours'
    end

    classes.join(' ')
  end
end

app/views/timesheets/_activities_popover.html.haml
- activities.each do |activity|
  %h4= activity.to_s
  %p= activity.remarks

app/views/timesheets/_show.html.haml
%table.table.collection
  %thead
    %tr
      %th= t_attr :date, Activity
      %th.right= t_attr :working_hours, Activity
      %th.right= t_attr :overtime, Activity
      %th.right= t_attr :overall_overtime, Activity
  %tbody
    - work_days.each do |day|
      - tr_params = {:class => work_day_classes(day)}
      - tr_params.merge!(:rel => 'popover', 'data-placement' => 'bottom', 'data-content' => h(render 'timesheets/activities_popover', :activities => day.activities), 'data-original-title' => 'Aktivitäten', 'data-html' => 'true') unless day.activities.empty?
      %tr{tr_params}
        %td
          - if day.activities.empty?
            = link_to l(day.date, :format => '%d.%m.%Y, %a'), new_person_activity_path(day.person, :activity => {:date => day.date.to_s(:db)}), 'data-href-container' => 'tr'
          - else
            = link_to l(day.date, :format => '%d.%m.%Y, %a'), person_activities_path(day.person, :by_date => day.date.to_s(:db)), 'data-href-container' => 'tr'
        %td.right
          %span.strong= "%0.2f" % day.hours_worked
          = "(%0.2f)" % day.hours_due
        %td.right.overtime.strong= "%0.2f" % day.overtime
        %td.right.overall-overtime.strong= "%0.2f" % day.overall_overtime

app/views/timesheets/index.html.haml
.contextual
  = contextual_link_to :new, Activity

= boot_page_title

= render 'show', :work_days => @work_days